// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry       = require("bs-platform/lib/js/curry.js");
var TextRe      = require("bs-react-native/lib/js/src/components/textRe.js");
var StyleRe     = require("bs-react-native/lib/js/src/styleRe.js");
var ReactNative = require("bs-react-native/lib/js/src/reactNative.js");
var ReasonReact = require("reason-react/lib/js/src/reasonReact.js");

function app() {
  return ReasonReact.element(/* None */0, /* None */0, Curry.app(ReactNative.View[/* make */0], [
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* Some */[StyleRe.style(/* :: */[
                          StyleRe.flex(1),
                          /* :: */[
                            StyleRe.justifyContent(/* center */98248149),
                            /* :: */[
                              StyleRe.alignItems(/* center */98248149),
                              /* [] */0
                            ]
                          ]
                        ])],
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* None */0,
                  /* array */[ReasonReact.element(/* None */0, /* None */0, TextRe.Text[/* make */0](/* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* None */0, /* Some */["Reason is awesome!"], /* array */[]))]
                ]));
}

exports.app = app;
/* TextRe Not a pure module */
